<?php

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<?php foreach ($media->mediaData() as $key => $value): ?>
  <?php if ($value): ?>
    <div class="meta-group more-meta-group">
      <h4><?php echo $translate(ucfirst($key)); ?></h4>
      <?php if ($key == "access" || $key == "master"): ?>
      <div class="value">
        <small>S3 Object URL (Not directly accessible)</small>
        <a href="<?php echo $escape($value); ?>"><?php echo $escape($value); ?></a>
      </div>
      <div class="get_presigned">
        <button class="button" id="download" data-file-type="<?php echo $key; ?>">
          <i class="fas fa-cloud-download-alt fa-lg" title="Download file"><span class="sr-only">Download file</span></i>
        </button>
        <button class="button" id="url" data-file-type="<?php echo $key; ?>">
          <i class="fas fa-link fa-lg" title="Get link for temporary acccess"><span class="sr-only">Get link for temporary acccess</span></i>
        </button>
      <?php if (isset($_POST['presigned'])): ?>
        <?php if ($_POST['presigned'] == $key): ?>
        <div id="presigned" data-<?php echo $key; ?>-presigned="<?php echo $this->s3presigned($escape($value)); ?>">
        </div>
        <?php endif;?>
      <?php endif;?>
      </div>
      <?php else:?>
        <div class="value">
          <a href="<?php echo $escape($value); ?>"><?php echo $escape($value); ?></a>
        </div>
      <?php endif;?>
    </div>
  <?php endif;?>
<?php endforeach; ?>
