<?php

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$labels = array('archival' => 'Archival package', 'replica' => 'Replica package', 'access' => 'Access file', 'mets' => 'METS file', 'thumbnail' => 'Thumbnail file', 'GoogleDriveID' => 'Google Drive Video ID', 'vimeoID' => 'Vimeo Video ID', 'YouTubeID' => 'YouTube Video ID', 'captions' => 'Captions file', 'iiif' => 'IIIF endpoint');
$access = $media->mediaData()['access'];
$iiifEndpoint = $this->setting('fit_module_aws_iiif_endpoint');
if ((strpos($media->mediaType(), 'image') === 0) && ($access) && ($iiifEndpoint)) {
  $parsed_url = parse_url($access);
  $key = ltrim($parsed_url["path"], '/');
  $extension = pathinfo($key, PATHINFO_EXTENSION);
  if ($extension == 'tif') {
    $iiif = $iiifEndpoint . str_replace("/", "%2F", substr($key, 0, -4)) . "/info.json";
  }
}
?>
<?php if (isset($iiif)): ?>
  <div class="meta-group more-meta-group">
    <h4>IIIF endpoint</h4>
    <div class="value">
      <a href="<?php echo $escape($iiif); ?>">
        <?php echo $escape($iiif); ?>
      </a>
    </div>
  </div>
<?php endif; ?>

<?php foreach ($media->mediaData() as $key => $value): ?>
  <?php if ($value): ?>
    <div class="meta-group more-meta-group">
      <?php if ($key == "access" || $key == "archival" || $key == "mets" || $key == "captions"): ?>
        <?php if ($this->userIsAllowed('Omeka\Entity\Site', 'create')): ?>
          <h4>
            <?php echo $labels[$key]; ?>
          </h4>
          <div class="value">
            <small>S3 Object URL (Not directly accessible)</small>
            <a href="<?php echo $escape($value); ?>">
              <?php echo $escape($value); ?>
            </a>
          </div>
          <div class="get_presigned">
            <button class="button" id="download" data-file-type="<?php echo $key; ?>">
              <i class="fas fa-cloud-download-alt fa-lg" title="Download file"><span class="sr-only">Download file</span></i>
            </button>
            <button class="button" id="url" data-file-type="<?php echo $key; ?>">
              <i class="fas fa-link fa-lg" title="Get link for temporary access"><span class="sr-only">Get link for temporary
                  access</span></i>
            </button>
            <?php if (isset($_POST['presigned'])): ?>
              <?php if ($_POST['presigned'] == $key): ?>
                <div id="presigned" data-<?php echo $key; ?>-presigned="<?php echo $this->s3presigned($escape($value), array_key_exists('download', $_POST) ? true : false); ?>">
                </div>
              <?php endif; ?>
            <?php endif; ?>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <h4>
          <?php echo $labels[$key]; ?>
        </h4>
        <div class="value">
          <?php if ($key == "YouTubeID"): ?>
            <?php echo $hyperlink->raw($escape($value) . ' <i class="fas fa-external-link-alt" title="Access on YouTube"><span class="sr-only">Access on YouTube</span></i>', 'https://www.youtube.com/watch?v=' . $value, ['target' => '_blank']); ?>
          <?php elseif ($key == "GoogleDriveID"): ?>
            <?php echo $hyperlink->raw($escape($value) . ' <i class="fas fa-external-link-alt" title="Access on Google Drive"><span class="sr-only">Access on Google Drive</span></i>', 'https://drive.google.com/file/d/' . $value . '/view', ['target' => '_blank']); ?>
          <?php elseif ($key == "vimeoID"): ?>
            <?php echo $hyperlink->raw($escape($value) . ' <i class="fas fa-external-link-alt" title="Access on Vimeo"><span class="sr-only">Access on Vimeo</span></i>', 'https://vimeo.com/' . $value, ['target' => '_blank']); ?>
          <?php else: ?>
            <?php if ($key == "replica"): ?>
              <small>S3 Glacier objects are only accessible upon request (please contact administrator for assistance)</small>
            <?php endif; ?>
            <a href="<?php echo $escape($value); ?>">
              <?php echo $escape($value); ?>
            </a>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
<?php endforeach; ?>