<?php
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/asset-hero.css', 'FITModule'));
?>
<div class="col-12 asset-heroes <?php echo $escape($className); ?>">
    <?php foreach ($attachments as $attachment): ?>
        <?php $asset = $attachment['asset']; ?>
        <?php $page = (array_key_exists('page', $attachment)) ? $attachment['page'] : null; ?>
        <div class="asset-hero card text-white border-0 rounded-0">
            <?php echo $this->thumbnail($asset, 'square', ['class' => 'card-img rounded-0']); ?>
            <?php if ($page): ?>
                <a href="<?php echo $escape($page->siteUrl()); ?>" class="stretched-link"></a>
            <?php endif; ?>
            <?php if ($attachment['caption'] !== ''): ?>
                <div class="card-body d-sm-none">
                    <div class="card-text fw-bold">
                        <?php echo $escape($attachment['caption']); ?>
                    </div>
                </div>
                <div class="card-img-overlay d-none d-sm-flex <?php echo $escape($alignment); ?>">
                    <div class="card-text">
                        <?php echo $escape($attachment['caption']); ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>