<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/item-showcase-hero-carousel.css', 'FITModule'));
?>
<?php $activated = false; ?>
<?php $id = 'carousel-' . rand(); ?>
<div class="col-10">
    <div class="row align-items-center justify-content-around item-showcase-hero-carousel">
        <div class="col-auto order-first pe-0">
            <button class="btn-arrow btnPrevious border-0 bg-transparent text-white" type="button" aria-label="Previous"
                data-bs-target="#<?php echo $id; ?>" data-bs-slide="prev">
                <i class="fas fa-chevron-left" aria-hidden="true" title="Previous">
                </i>
            </button>
        </div>
        <div class="col-auto order-last ps-0">
            <button class="btn-arrow btnNext border-0 bg-transparent text-white" type="button" aria-label="Next"
                data-bs-target="#<?php echo $id; ?>" data-bs-slide="next">
                <i class="fas fa-chevron-right" aria-hidden="true" title="Next">
                </i>
            </button>
        </div>
        <div class="col px-3 px-xl-4">
            <div id="<?php echo $id; ?>" class="carousel slide" data-bs-ride="true">
                <div class="carousel-inner">
                    <?php foreach ($attachments as $attachment): ?>
                        <?php $item = $attachment->item(); ?>
                        <?php if ($item): ?>
                            <?php $media = $attachment->media() ?: $item->primaryMedia(); ?>
                            <?php if ($media): ?>
                                <div class="carousel-item<?php echo $activated ? "" : " active"; ?>">

                                    <a class="card text-white border-0 rounded-0" href="<?php echo $item->siteUrl(); ?>">
                                        <?php echo $this->thumbnail($media, $this->thumbnailType, ['class' => 'card-img rounded-0', 'alt' => $item->displayTitle()]); ?>
                                        <div class="card-img-overlay d-flex align-items-center">
                                            <div class="card-body">
                                                <?php $showTitleOption = $this->showTitleOption; ?>
                                                <?php if ($showTitleOption == 'item_title'): ?>
                                                    <h2 class="card-title">
                                                        <?php echo $item->displayTitle(); ?>
                                                    </h2>
                                                <?php elseif ($showTitleOption == 'file_name'): ?>
                                                    <h2 class="card-title">
                                                        <?php echo $media->displayTitle(); ?>
                                                    </h2>
                                                <?php endif; ?>
                                                <?php $caption = $attachment->caption(); ?>
                                                <?php if ($caption): ?>
                                                    <div class="caption card-text">
                                                        <?php echo $caption; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <?php $activated = true; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>