<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'login');
?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1><?php echo $translate('Log in'); ?></h1>
            <?php echo $this->form($form); ?>
            <p class="forgot-password"><?php echo $this->hyperlink($translate('Forgot password?'), $this->url('forgot-password')); ?></p>
        </div>
    </div>
</div>